name: grib_kerchunk
channels:
  - conda-forge
  - defaults
dependencies: 
 - python=3.9
 - fsspec
 - s3fs=2022.11.0
 - boto3 
 - pip 
 - zarr 
 - cfgrib
 - numcodecs
 - pip:
   - git+https://github.com/fsspec/kerchunk
   - awslambdaric